### PR TITLE
Bugfixes - correct partOf and hide non-public items

### LINKED ISSUE #166: Storage-Collections showing incorrect root "partOf"
This issue relates to the `"partOf"` property for a storage-collection that is a first child of `root` when fetched via flat uri.

* `"id"` is the hierarchical path (ie `/{customer}` but it should be `/{customer}/collections/root`
* `"label"` is the label of the current item (ie the first-child) but it should be the label of the parent.

Verify whether this happens to all `"partOf"` (ie is it just for first-child of root or any level of hierarchy)

### PR DESCRIPTION
**Pull request by donaldgray**
Fixes #166 and #167

## #166 - incorrect `"partOf"`

Introduced a couple of navigation properties; `Hierarchy` gains `ParentCollection` and `Collection` gains `Children`. It's unlikely that the latter will be used but it's there should we need it. The former allows us to load the parent of the current collection when rendering collection to set the `"partOf"` - previously it was using current collections label and redirecting to parent hierarchical path - now it's using parent label and parent flat-id.

Renamed `ToFlatCollection` to `ToPresentationCollection` to reflect the name of the return type.

## #167 - exclude non-public from `"items"` in hierarchical collection

This was adding a bool to `RetrieveCollectionItems` in `GetHierarchicalCollection` but also slightly refactored this:
* Rather than checking if collection is public or not in calling controller, encapsulate that logic in the request handler, this shortcuts the request and moves the decision making into the handler.
* Use multiple returns; there are 2 distinct paths for iiif-collection or storage-collection so have a return in each. These fall through to a single `empty` return for any cases that can't be fulfulled

### CODE REVIEW

File: src/IIIFPresentation/API/Converters/CollectionConverter.cs [hunk 1]
```diff
@@ -132,36 +132,33 @@ public static List<string> GenerateContext()
...
+    public static List<ResourceBase>? GeneratePartOf(DbCollection? collection,
+        IPathGenerator pathGenerator) =>
+        collection != null
+            ?
+            [
+                new ExternalResource(nameof(PresentationType.Collection))
                 {
-                    Id = pathGenerator.GenerateHierarchicalCollectionParent(collection, hierarchy),
-                    Label = collection.Label
+                    Id = pathGenerator.GenerateFlatCollectionId(collection),
```
Comment (JackLewis-digirati) [inline src/IIIFPresentation/API/Converters/CollectionConverter.cs:157]: Should this be changed to `GeneratePresentationCollectionId` given the rename

Comment (donaldgray) [reply src/IIIFPresentation/API/Converters/CollectionConverter.cs:157]: I don't think so, renaming `ToFlatCollection()` -> `ToPresentationCollection()` is to match the return type (`FlatCollection` was renamed to `PresentationCollection` in #47).

I think the flat methods on `IPathGenerator` still make sense as the paths are flat (or hierarchical). If we want to revisit we can do and rename all methods in `IPathGenerator` that refer to 'flat' paths.
