### PR TITLE
Disallow IIIF collections from being used as a parent

### LINKED ISSUE #286: Parent collection `items` not updated after creating a child via hierarchical POST
**Steps to reproduce**

1. Create a parent collection via a hierarchical URL - POST `.../{customer_id}/parent_collection`
```
...Payload
{
  "type": "Collection",
  "behavior": [
    "public-iiif",
  ]
}
```
2. Create a child collection using the same payload - POST `.../{customer_id}/parent_collection/child_collection`
The ID of the returned collection should show that it is a descendant of `parent_collection`
```
...Hierarchical
{
    "@context": "http://iiif.io/api/presentation/3/context.json",
    "id": "https://presentation-api.dlcs.digirati.io/52/my_parent_collection/my_child_collection"
    "type": "Collection"
}
```
```
...Presentation
{
    "publicId": "https://presentation-api.dlcs.digirati.io/52/my_parent_collection/my_child_collection",
    "flatId": "8k21jnv04iy1qp8ggl7crvc",
    "slug": "my_child_collection",
    "parent": "https://presentation-api.dlcs.digirati.io/52/collections/efufc50avqnx4zfiqdt6syn",
    "itemsOrder": 0,
    "created": "2025-02-20T11:46:18Z",
    "modified": "2025-02-20T11:46:18Z",
    "createdBy": "Admin",
    "@context": [
        "http://tbc.org/iiif-repository/1/context.json",
        "http://iiif.io/api/presentation/3/context.json"
    ],
    "id": "https://presentation-api.dlcs.digirati.io/52/collections/8k21jnv04iy1qp8ggl7crvc",
    "type": "Collection",
    "behavior": [
        "public-iiif"
    ]
}
```
3. Retrieve the parent - `items` is still undefined
(NOTE: "id" in hierarchical form is wrong, see https://github.com/dlcs/iiif-presentation/issues/281)
```
...Hierarchical
{
    "@context": "http://iiif.io/api/presentation/3/context.json",
    "id": "https://presentation-api.dlcs.digirati.io/52",
    "type": "Collection"
}
```
```
...Presentation
{
    "publicId": "https://presentation-api.dlcs.digirati.io/52/my_parent_collection",
    "flatId": "efufc50avqnx4zfiqdt6syn",
    "slug": "my_parent_collection",
    "parent": "https://presentation-api.dlcs.digirati.io/52/collections/root",
    "itemsOrder": 0,
    "created": "2025-02-20T11:46:14Z",
    "modified": "2025-02-20T11:46:14Z",
    "createdBy": "Admin",
    "@context": [
        "http://tbc.org/iiif-repository/1/context.json",
        "http://iiif.io/api/presentation/3/context.json"
    ],
    "id": "https://presentation-api.dlcs.digirati.io/52/collections/efufc50avqnx4zfiqdt6syn",
    "type": "Collection",
    "behavior": [
        "public-iiif"
    ]
}
```

### PR DESCRIPTION
**Pull request by JackLewis-digirati**
Resolves #286 

This PR makes it so that a IIIF collection cannot be used as a parent resource on all resources, rather than just manifests

### CODE REVIEW

**Review by griffri — APPROVED** [review]

File: src/IIIFPresentation/API/Features/Common/Helpers/ParentValidator.cs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+using API.Infrastructure.Requests;
+using IIIF;
+using Models.API.General;
+using Models.Database.Collections;
+
+namespace API.Features.Common.Helpers;
+
+public static class ParentValidator
+{
+    public static ModifyEntityResult<TCollection, ModifyCollectionType>? ValidateParentCollection<TCollection>(Collection? parentCollection)
```
Comment (donaldgray) [inline src/IIIFPresentation/API/Features/Common/Helpers/ParentValidator.cs:11]: XML doc for what's being validated?

File: src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs [hunk 2]
```diff
@@ -52,7 +53,9 @@ public async Task<ModifyEntityResult<Collection, ModifyCollectionType>> Handle(P
         var parentCollection =
             await dbContext.RetrieveHierarchy(request.CustomerId, parentSlug, cancellationToken);
         
-        if (parentCollection == null) return ErrorHelper.NullParentResponse<Collection>();
+        var parentValidationError =
+            ParentValidator.ValidateParentCollection<Collection>(parentCollection.Collection);
```
Comment (donaldgray) [inline src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs:57]: Is `parentCollection` guaranteed to have a value? Should this be `parentCollection?.Collection` or validate that `parentCollection != null` before passing?

This also differs from `CreateCollection` and `ManifestWriteService` in that it calls `dbContext.RetrieveHierarchy` to get parent, rather than `dbContext.RetrieveCollectionAsync` - why the difference?

**Review by donaldgray — CHANGES_REQUESTED** [review]
The parent validation is missing from `UpsertCollection`.

The same validation is required in 4 places: `ManifestWriteService`, `CreateCollection`, `PostHierarchicalCollection` and `UpsertCollection`. It feels like something that should happen in 1 place, if that were the case then we'd not run the risk of missing one (`UpsertCollection` in this case). Would it be possible to have it happen in 1 place? If too large a refactor then can be capture somewhere (#291 maybe?)

**Review by donaldgray — APPROVED** [review]
