### PR TITLE
Fix label from items to work correctly with a matched canvas

### LINKED ISSUE #501: `canvasLabel` and `label` validation not matching the manifest merger behavior in the canvas painting merger
During testing it was noticed that the following payload wasn't working

```
{
  "type": "Manifest",
  "label": {
    "en": [
      "Mixed Manifest Tests - Painted resource with matched canvas, and a matching label"
    ]
  },
  "behavior": [
    "paged"
  ],
  "items": [
    {
      "id": "example",
      "type": "Canvas",
      "label": {
        "en": [
          "my-label"
        ]
      }
    }
  ],
  "paintedResources": [
    {
      "asset": {
        "id": "example",
        "mediaType": "image/jpeg",
        "origin": ""
      },
      "canvasPainting": {
        "canvasId": "painted-resource-example",
        "canvasOrder": 0,
        "label": {
          "en": [
            "my-label"
          ]
        }
      }
    }
  ],
  "slug": "0009,
  "parent": "root"
}
```

where it was getting back a bad request due to not matching label as `item` sets `canvasLabel`, but `paintedResource` sets `label`, while also defaulting `canvasLabel` to the `canvasLabel` of `item` when merging canvas paintings

This is different behaviour to that discussed in the [docs around `canvasLabel` and `label`](https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/iiif#canvaspainting) where the `label` value _should_ have been picked up for use as `canvasLabel`

Additionally, the validation needs to take into account "the first non-null value for label and canvasLabel for matching", whereas currently matching _ONLY_ occurs on the equivalent `canvasPainting` from `item`

see #393 for further details on how this was fixed in the manifest merger

### PR DESCRIPTION
**Pull request by JackLewis-digirati**
Resolves #501

This PR makes it so that `canvasLabel` and `label` work consistently across `items` and `canvasPainting` when in a matched canvas.  

Essentially, the `items.label` value will act like `canvasPainting.CanvasLabel`, and as such there is a removed check on `label` in the `canvasPaintingMerger` and will override the first `canvasPainting.CanvasLabel` if no `CanvasLabel` is set

See additional scenarios for how this will work in the above bug ticket

### CODE REVIEW

File: src/IIIFPresentation/API/Features/Manifest/CanvasPaintingMerger.cs [hunk 1]
```diff
@@ -92,7 +93,8 @@ private void JoinPaintedResourcesWithItems(List<InterimCanvasPainting> itemsCanv
         {
             var matchedPaintedResourceCanvasPaintings = paintedResourceCanvasPaintings.Where(cp =>
                 !string.IsNullOrEmpty(cp.Id) && string.Equals(cp.Id, itemsCanvasPainting.Id,
-                    StringComparison.OrdinalIgnoreCase)).ToList();
+                    StringComparison.OrdinalIgnoreCase)).OrderBy(cp => cp.CanvasOrder)
```
Comment (donaldgray) [inline src/IIIFPresentation/API/Features/Manifest/CanvasPaintingMerger.cs]: I think `.OrderBy(cp => cp.CanvasOrder).ThenBy(cp => cp.ChoiceOrder)` is used in a few places - is it worth having this as a reusable method?

File: src/IIIFPresentation/API/Features/Manifest/CanvasPaintingMerger.cs [hunk 2]
```diff
@@ -169,31 +182,35 @@ private void ValidateItemCanvasPainting(InterimCanvasPainting itemsCanvasPaintin
                     $"Canvas painting with id {itemsCanvasPainting.Id} cannot contain an annotation body");
             }
         }
-
-        if (paintedResourceCanvasPainting.CanvasLabel == null && itemsCanvasPainting.CanvasLabel != null)
+        
+        if (paintedResourceCanvasPainting.CanvasLabel == null &&
```
Comment (donaldgray) [inline src/IIIFPresentation/API/Features/Manifest/CanvasPaintingMerger.cs]: Comment explaining? Or can it be extracted into a method? `if (SomethingExplanatory()) { ... }`

File: src/IIIFPresentation/Services/Manifests/Helpers/InterimCanvasPaintingX.cs [hunk 3]
```diff
@@ -88,4 +88,8 @@ public static List<CanvasPainting> ConvertInterimCanvasPaintings(
         this List<InterimCanvasPainting>? interimCanvasPaintings) =>
         interimCanvasPaintings?.Where(icp =>
             icp is { SuspectedAssetId: not null, CanvasPaintingType: CanvasPaintingType.Items }).ToList();
+
+    public static IEnumerable<InterimCanvasPainting> OrderInterimCanvasPaintings(
```
Comment (donaldgray) [inline src/IIIFPresentation/Services/Manifests/Helpers/InterimCanvasPaintingX.cs]: `CanvasOrder` and `ChoiceOrder` aren't specific to `InterimCanvasPainting`, neither is the logic to `.OrderBy(cp => cp.CanvasOrder).ThenBy(cp => cp.ChoiceOrder)`, those are relevant to `CanvasPainting` too.

If this method was also usable for `CanvasPainting` then it would have more utility and could be used https://github.com/dlcs/iiif-presentation/blob/develop/src/IIIFPresentation/Services/Manifests/ManifestMerger.cs#L101-L102 and https://github.com/dlcs/iiif-presentation/blob/develop/src/IIIFPresentation/API/Converters/ManifestConverter.cs#L173-L174 (or could replace that `ManifestConverter` method entirely).
